#!/usr/bin/env bash
# shellcheck disable=SC2317,SC2329,SC2034,SC2016  # mocks/config are invoked/read indirectly by the extracted code; literal backticks/fences are intentional
#
# Tests for the "what was done" close summary the loop posts on an issue once it
# resolves it (#161/#217). #161 asked for a cheap summary of what was done to be
# posted on the issue; it was only wired into the TUI's manual-close path, so in
# normal autonomous operation -- where the loop opens a PR and GitHub closes the
# issue on merge -- no summary was ever posted (#217). The loop now writes the
# summary itself when it marks an issue done.
#
# The real code is exercised by extracting the marked blocks and driving them
# with mocks -- no GitHub and no model are touched. The user-observable behaviour
# is: a resolved issue gets one summary comment, generated by the light model,
# naming that model and tagged with a hidden marker; and nothing is posted (and
# no model is spent) when the feature is off or the issue was never worked.
#
# Run: tests/close-summary.test.sh
set -uo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
script="$here/../copilot-loop.sh"

[ -f "$script" ] || { echo "cannot find copilot-loop.sh next to tests/"; exit 1; }

extract() {
  local block; block="$(sed -n "/# >>> $1 >>>/,/# <<< $1 <<</p" "$script")"
  [ -n "$block" ] || { echo "could not extract '$1' (markers missing?)"; exit 1; }
  eval "$block"
}
extract "summary helpers"        # summary_enabled, resolve_summary_model, _summary_header,
                                 # build_summary_prompt, clean_summary, build_summary_comment
extract "summary report helpers" # build_issue_summary, _report_summary

fail=0
assert_eq() {
  local desc="$1" got="$2" want="$3"
  if [ "$got" = "$want" ]; then
    printf 'ok   - %s\n' "$desc"
  else
    printf 'FAIL - %s\n       got:  [%s]\n       want: [%s]\n' "$desc" "$got" "$want"
    fail=1
  fi
}
assert_contains() {
  local desc="$1" hay="$2" needle="$3"
  case "$hay" in
    *"$needle"*) printf 'ok   - %s\n' "$desc" ;;
    *)           printf 'FAIL - %s\n       [%s]\n       does not contain [%s]\n' "$desc" "$hay" "$needle"; fail=1 ;;
  esac
}
assert_not_contains() {
  local desc="$1" hay="$2" needle="$3"
  case "$hay" in
    *"$needle"*) printf 'FAIL - %s\n       [%s]\n       unexpectedly contains [%s]\n' "$desc" "$hay" "$needle"; fail=1 ;;
    *)           printf 'ok   - %s\n' "$desc" ;;
  esac
}

# ============================================================================
# summary_enabled: on by default, off only for the explicit falsy spellings
# ============================================================================
assert_eq "unset -> on"        "$(summary_enabled '')"        "1"
assert_eq "'1' -> on"          "$(summary_enabled '1')"       "1"
assert_eq "'off' -> off"       "$(summary_enabled 'off')"     "0"
assert_eq "'0' -> off"         "$(summary_enabled '0')"       "0"
assert_eq "'false' -> off"     "$(summary_enabled 'false')"   "0"
assert_eq "'no' -> off"        "$(summary_enabled 'no')"      "0"
assert_eq "'disabled' -> off"  "$(summary_enabled 'disabled')" "0"

# ============================================================================
# resolve_summary_model: cheap built-in by default, "auto"/off let Copilot pick
# ============================================================================
assert_eq "unset -> built-in light model" "$(resolve_summary_model '')"       "gpt-5-mini"
assert_eq "'auto' -> Copilot picks"       "$(resolve_summary_model 'auto')"   ""
assert_eq "'AUTO' -> Copilot picks"       "$(resolve_summary_model 'AUTO')"   ""
assert_eq "'off' -> Copilot picks"        "$(resolve_summary_model 'off')"    ""
assert_eq "'none' -> Copilot picks"       "$(resolve_summary_model 'none')"   ""
assert_eq "'0' -> Copilot picks"          "$(resolve_summary_model '0')"      ""
assert_eq "explicit id used verbatim"     "$(resolve_summary_model '  claude-opus-4.5 ')" "claude-opus-4.5"

# ============================================================================
# _summary_header: always records which model wrote the summary
# ============================================================================
assert_contains "header names the model" "$(_summary_header 'gpt-5-mini')" 'model: `gpt-5-mini`'
assert_contains "empty model -> auto"    "$(_summary_header '')"           'model: `auto`'
assert_contains "header labels a closing summary" "$(_summary_header 'x')" 'Closing summary'

# ============================================================================
# clean_summary: strips a wrapping code fence and trims blank edges
# ============================================================================
fenced="$(printf '```markdown\n**Did** the thing.\n\n\n```\n' | clean_summary)"
assert_eq       "fence + blank edges stripped" "$fenced" "**Did** the thing."
assert_not_contains "no stray backtick fence" "$fenced" '```'

# ============================================================================
# build_summary_prompt: gives the model the issue and its session log
# ============================================================================
prompt="$(build_summary_prompt 42 'Fix the widget' 'branch created; PR #9 opened')"
assert_contains "prompt names the issue number" "$prompt" '#42'
assert_contains "prompt names the issue title"  "$prompt" 'Fix the widget'
assert_contains "prompt carries the session log" "$prompt" 'PR #9 opened'

# ============================================================================
# build_summary_comment: header + summary + hidden marker, in that order
# ============================================================================
comment="$(build_summary_comment 'Opened PR #9.' 'gpt-5-mini' '<!-- copilot-loop:summary -->')"
assert_contains "comment carries the summary" "$comment" 'Opened PR #9.'
assert_contains "comment names the model"     "$comment" 'model: `gpt-5-mini`'
assert_contains "comment carries the marker"  "$comment" '<!-- copilot-loop:summary -->'

# ============================================================================
# End-to-end: what a user sees on a resolved issue. The REAL build_issue_summary
# and _report_summary run; only the model call (_run_with_timeout) and the GitHub
# comment (gh) are mocked, so no model is spent and nothing is posted for real.
# ============================================================================
SUMMARY_MARKER="<!-- copilot-loop:summary -->"

MODEL_RAW=""                                   # what the "model" prints
MODEL_CALLS_FILE="$(mktemp)"; : >"$MODEL_CALLS_FILE"
model_calls() { wc -l <"$MODEL_CALLS_FILE" | tr -d ' '; }
# Stub the time-boxed model call: record it and print the canned summary. Runs in
# the $(...) subshell of build_issue_summary, so record via a file.
_run_with_timeout() { echo x >>"$MODEL_CALLS_FILE"; printf '%s' "$MODEL_RAW"; }

GH_BODY_FILE="$(mktemp)"; : >"$GH_BODY_FILE"
posted_body() { cat "$GH_BODY_FILE"; }
# Record the --body of an `issue comment` call so the posted summary is inspectable.
gh() {
  if [ "${1:-}" = issue ] && [ "${2:-}" = comment ]; then
    local prev=""
    for a in "$@"; do
      [ "$prev" = "--body" ] && printf '%s' "$a" >>"$GH_BODY_FILE"
      prev="$a"
    done
  fi
  return 0
}

tmp="$(mktemp -d 2>/dev/null || mktemp -d -t closesummary)"
trap 'rm -rf "$tmp" "$MODEL_CALLS_FILE" "$GH_BODY_FILE"' EXIT

# A realistic session log: loop narration (branch/PR) plus a colourful Copilot
# line, so the ANSI/CSI strip is exercised on the way to the model.
log="$tmp/issue-9.log"
printf 'Created branch copilot/9-add-summary\n\033[32mCopilot: edited copilot-loop.sh\033[0m\nissue #9: DONE -> https://github.com/o/r/pull/9\n' >"$log"

# --- default (on): the resolved issue gets a summary comment -----------------
REPORT_SUMMARY=1
MODEL_RAW='Added a `--summary` flag and posted the closing summary. Opened PR #9.'
: >"$GH_BODY_FILE"; : >"$MODEL_CALLS_FILE"
_report_summary 9 "There is no summary on the issues" "$log" "gpt-5-mini"
assert_eq       "summary on: the model was consulted once" "$(model_calls)" "1"
assert_contains "a summary comment is posted"        "$(posted_body)" 'Opened PR #9.'
assert_contains "the comment names the light model"  "$(posted_body)" 'model: `gpt-5-mini`'
assert_contains "the comment is tagged with the marker" "$(posted_body)" "$SUMMARY_MARKER"

# --- the model wrapping its whole reply in a fence is cleaned before posting --
REPORT_SUMMARY=1
MODEL_RAW="$(printf '```\nResolved by opening PR #9.\n```')"
: >"$GH_BODY_FILE"; : >"$MODEL_CALLS_FILE"
_report_summary 9 "t" "$log" "gpt-5-mini"
assert_contains "fenced reply still posts the summary text" "$(posted_body)" 'Resolved by opening PR #9.'
assert_not_contains "posted comment has no stray fence"     "$(posted_body)" '```'

# --- off (--no-summary): nothing is posted and no model is spent -------------
REPORT_SUMMARY=0
MODEL_RAW='should never be used'
: >"$GH_BODY_FILE"; : >"$MODEL_CALLS_FILE"
_report_summary 9 "t" "$log" "gpt-5-mini"
assert_eq "summary off: no comment posted" "$(posted_body)" ""
assert_eq "summary off: model not spent"   "$(model_calls)" "0"

# --- an issue the loop never worked (no session log) gets no summary ----------
REPORT_SUMMARY=1
MODEL_RAW='should never be used'
: >"$GH_BODY_FILE"; : >"$MODEL_CALLS_FILE"
_report_summary 9 "t" "$tmp/does-not-exist.log" "gpt-5-mini"
assert_eq "no log: no comment posted" "$(posted_body)" ""
assert_eq "no log: model not spent"   "$(model_calls)" "0"

# --- a log with no real content (only whitespace) posts nothing --------------
REPORT_SUMMARY=1
MODEL_RAW='should never be used'
blank_log="$tmp/blank.log"; printf '   \n\t\n \n' >"$blank_log"
: >"$GH_BODY_FILE"; : >"$MODEL_CALLS_FILE"
_report_summary 9 "t" "$blank_log" "gpt-5-mini"
assert_eq "blank log: no comment posted" "$(posted_body)" ""
assert_eq "blank log: model not spent"   "$(model_calls)" "0"

# --- the model returning nothing usable posts nothing (no empty comment) ------
REPORT_SUMMARY=1
MODEL_RAW=''
: >"$GH_BODY_FILE"; : >"$MODEL_CALLS_FILE"
_report_summary 9 "t" "$log" "gpt-5-mini"
assert_eq "empty model reply: no comment posted" "$(posted_body)" ""

if [ "$fail" -eq 0 ]; then
  echo "All close-summary tests passed."
else
  echo "Some close-summary tests FAILED."
fi
exit "$fail"
