//! Background close-summary reporting for the TUI (#161).
//!
//! When an issue is closed in the TUI, `copilot-loop` can post a comment
//! summarizing what was done, generated by a *light* model so it stays cheap.
//! The model call (and the `gh issue comment` that follows) can take seconds, so
//! — like the issue fetcher (#144) — it runs on a dedicated worker thread: the UI
//! thread hands off a request and picks up the outcome on a later tick, never
//! blocking input or redraws while a summary is written.

use std::sync::mpsc::{self, Receiver, Sender};
use std::thread::{self, JoinHandle};

use anyhow::Result;

use crate::github;

/// A request to summarize a just-closed issue's session and post it as a comment.
pub struct ReportRequest {
    /// The closed issue's number.
    pub number: u64,
    /// The issue title, for the summary prompt.
    pub title: String,
    /// The light model to summarize with, or `None` to let Copilot pick.
    pub model: Option<String>,
    /// The (capped, sanitized) tail of the issue's session log — the context the
    /// model summarizes. Empty when the issue has no loop log.
    pub context: String,
}

/// Whether a report posted a comment or found nothing to summarize.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReportStatus {
    /// A summary was generated and posted as a comment.
    Posted,
    /// The issue had no session log, so nothing was summarized or posted.
    NoContext,
}

/// A completed report: which issue it was for, and whether it posted (or why not,
/// or the error that stopped it).
pub struct ReportOutcome {
    pub number: u64,
    pub result: Result<ReportStatus>,
}

/// Handle to the background reporter thread. The UI thread submits requests and
/// drains outcomes through it. Dropping it closes the request channel, ending the
/// worker.
pub struct CloseReporter {
    requests: Sender<ReportRequest>,
    outcomes: Receiver<ReportOutcome>,
    // Kept so the thread is joined on drop rather than detached; the worker exits
    // promptly once `requests` is dropped and its `recv` returns `Err`.
    _handle: JoinHandle<()>,
}

impl CloseReporter {
    /// Spawn the reporter worker.
    pub fn spawn() -> Self {
        let (req_tx, req_rx) = mpsc::channel::<ReportRequest>();
        let (out_tx, out_rx) = mpsc::channel::<ReportOutcome>();
        let handle = thread::spawn(move || report_loop(&req_rx, &out_tx));
        Self {
            requests: req_tx,
            outcomes: out_rx,
            _handle: handle,
        }
    }

    /// Submit a report. Non-blocking; a dead worker is ignored since the summary
    /// is best-effort — the issue is already closed.
    pub fn request(&self, request: ReportRequest) {
        let _ = self.requests.send(request);
    }

    /// Take every completed report, oldest first, without blocking.
    pub fn drain(&self) -> Vec<ReportOutcome> {
        self.outcomes.try_iter().collect()
    }
}

/// The worker loop: block for a request, run it, and send the outcome. Ends when
/// the request channel closes (the UI dropped the reporter) or the UI stops
/// receiving outcomes.
fn report_loop(requests: &Receiver<ReportRequest>, outcomes: &Sender<ReportOutcome>) {
    while let Ok(request) = requests.recv() {
        let number = request.number;
        let outcome = ReportOutcome {
            number,
            result: run_report(request),
        };
        if outcomes.send(outcome).is_err() {
            break;
        }
    }
}

/// Run one report: summarize the session with the light model and post it as a
/// comment. Skips (without an error) when there is no session context, so an
/// issue closed by hand — never worked by the loop — is not summarized.
fn run_report(request: ReportRequest) -> Result<ReportStatus> {
    if request.context.trim().is_empty() {
        return Ok(ReportStatus::NoContext);
    }

    let summary = github::summarize_session(
        request.number,
        &request.title,
        &request.context,
        request.model.as_deref(),
    )?;
    let body = build_comment(&summary, request.model.as_deref());
    github::comment_issue(request.number, &body)?;
    Ok(ReportStatus::Posted)
}

/// Marker appended to the summary comment so it is recognisable as an
/// auto-generated close summary (mirrors the loop's usage-comment marker).
const SUMMARY_MARKER: &str = "<!-- copilot-loop:summary -->";

/// Wrap a model's summary in the comment body posted to the issue: a short header
/// naming it as an automated close summary (with the model used), the summary
/// itself, and a hidden marker. Pure for testing.
fn build_comment(summary: &str, model: Option<&str>) -> String {
    let model_label = model.unwrap_or("auto");
    format!(
        "🤖 **Closing summary** — what the loop did, per its session (model: `{model_label}`).\n\n\
{summary}\n\n\
{SUMMARY_MARKER}"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn run_report_skips_when_there_is_no_context() {
        let outcome = run_report(ReportRequest {
            number: 42,
            title: "no log".to_string(),
            model: Some("gpt-5-mini".to_string()),
            context: "   \n  ".to_string(),
        });
        assert_eq!(outcome.unwrap(), ReportStatus::NoContext);
    }

    #[test]
    fn run_report_posts_when_context_is_present() {
        // `github::summarize_session`/`comment_issue` are hermetic under `cfg!(test)`
        // (no `copilot`/`gh` call), so this exercises the whole flow offline.
        let outcome = run_report(ReportRequest {
            number: 7,
            title: "did work".to_string(),
            model: None,
            context: "branch created\nPR #9 opened".to_string(),
        });
        assert_eq!(outcome.unwrap(), ReportStatus::Posted);
    }

    #[test]
    fn build_comment_carries_the_summary_marker_and_model() {
        let body = build_comment("Did the thing.", Some("gpt-5-mini"));
        assert!(body.contains("Did the thing."));
        assert!(body.contains("gpt-5-mini"));
        assert!(body.contains(SUMMARY_MARKER));
    }

    #[test]
    fn build_comment_labels_an_auto_model() {
        let body = build_comment("summary", None);
        assert!(body.contains("`auto`"));
    }

    #[test]
    fn drain_is_empty_before_any_outcome() {
        // A fresh reporter has produced nothing yet, so draining yields nothing
        // and never blocks. No request is sent, so no summary runs.
        let reporter = CloseReporter::spawn();
        assert!(reporter.drain().is_empty());
    }

    #[test]
    fn drain_returns_outcomes_oldest_first() {
        // Drive the outcome side directly: push two outcomes and confirm
        // `try_iter` hands them back in order.
        let (out_tx, out_rx) = mpsc::channel::<ReportOutcome>();
        out_tx
            .send(ReportOutcome {
                number: 1,
                result: Ok(ReportStatus::Posted),
            })
            .unwrap();
        out_tx
            .send(ReportOutcome {
                number: 2,
                result: Err(anyhow::anyhow!("boom")),
            })
            .unwrap();

        let drained: Vec<_> = out_rx.try_iter().collect();
        assert_eq!(drained.len(), 2);
        assert_eq!(drained[0].number, 1);
        assert!(drained[0].result.is_ok());
        assert_eq!(drained[1].number, 2);
        assert!(drained[1].result.is_err());
        assert!(out_rx.try_iter().next().is_none());
    }

    #[test]
    fn request_after_the_worker_exits_is_ignored() {
        // Dropping the outcome receiver ends the worker; a later request must not
        // panic (the summary is best-effort — the issue is already closed).
        let reporter = CloseReporter::spawn();
        reporter.request(ReportRequest {
            number: 5,
            title: "t".to_string(),
            model: None,
            context: String::new(),
        });
    }
}
